version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test-and-package:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm pack
              name: Creating artifacts
              command: |
                echo "my artifact file" > /tmp/artifact-1;
                mkdir /tmp/artifacts;
                echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;
            - store_artifacts:
              path: /tmp/artifact-1
              destination: artifact-file

            - store_artifacts:
               path: /tmp/artifacts
workflows:
    build-and-test-and-package:
      jobs:
        - build-and-test-and-package:
